# Generated by Django 4.2.13 on 2024-06-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_arte_precio_arte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
