# Generated by Django 4.2.13 on 2024-06-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_artista_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
