# Generated by Django 4.2.13 on 2024-07-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_art_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arte',
        ),
        migrations.RenameField(
            model_name='artista',
            old_name='nombre_Artista',
            new_name='nombre_artista',
        ),
        migrations.RenameField(
            model_name='artista',
            old_name='rut_Artista',
            new_name='rut_artista',
        ),
        migrations.RenameField(
            model_name='artista',
            old_name='Telefono',
            new_name='telefono',
        ),
        migrations.AddField(
            model_name='art',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='art',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='art',
            name='style',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
